# Generated by Django 4.0.5 on 2022-06-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('unitprice', models.IntegerField(blank=True, db_column='unitPrice', null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField()),
                ('categoryid', models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.DO_NOTHING, to='api.categories')),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('buyerid', models.ForeignKey(db_column='buyerId', on_delete=django.db.models.deletion.CASCADE, to='api.users')),
                ('productid', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='api.products')),
            ],
            options={
                'db_table': 'offers',
            },
        ),
    ]
