# Generated by Django 4.0.5 on 2022-07-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_description_products_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Offers',
            new_name='Offer',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
