# Generated by Django 4.0.5 on 2022-07-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_id_alter_offer_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unitprice',
            new_name='price',
        ),
        migrations.AddField(
            model_name='offer',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
