# Generated by Django 4.0.5 on 2022-07-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_unitprice_product_price_offer_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='buyerid',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='productid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categoryid',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
